### PR TITLE
Added generic background_data and android_background_data key.

### PR DESCRIPTION
**Pull request by robtaireeo**

### CODE REVIEW

**Comment by flovilmart** [comment]
Can you add a test for both iOS background data options?

**Comment by robtaireeo** [comment]
@flovilmart I have moved the 'background_data' test into its own, and the android and ios tests just use their respective keys.

**Comment by robtaireeo** [comment]
@flovilmart are the new tests okay?

**Comment by flovilmart** [comment]
It seems to be ok, didn't get the time to go through it

**Comment by MattiaConfalonieri** [comment]
Sorry is this PR about my issue?
https://github.com/parse-server-modules/parse-server-onesignal-push-adapter/issues/12

**Pull request merged**
